//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNavi.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopNavi.Resources.TextResource", typeof(TextResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept data from this person.
        /// </summary>
        internal static string AcceptDataFromThisPerson {
            get {
                return ResourceManager.GetString("AcceptDataFromThisPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic confirmation.
        /// </summary>
        internal static string AutoOk {
            get {
                return ResourceManager.GetString("AutoOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available stores:.
        /// </summary>
        internal static string AvailableStores {
            get {
                return ResourceManager.GetString("AvailableStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel List.
        /// </summary>
        internal static string CarouselList {
            get {
                return ResourceManager.GetString("CarouselList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud/SMS.
        /// </summary>
        internal static string CloudSMS {
            get {
                return ResourceManager.GetString("CloudSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create list.
        /// </summary>
        internal static string CreateList {
            get {
                return ResourceManager.GetString("CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local menu for list operations (please hold).
        /// </summary>
        internal static string CreateListMenuItem {
            get {
                return ResourceManager.GetString("CreateListMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local menu containg list operations.
        /// </summary>
        internal static string CreateListMenuItemDescr {
            get {
                return ResourceManager.GetString("CreateListMenuItemDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete finished.
        /// </summary>
        internal static string DeleteFinished {
            get {
                return ResourceManager.GetString("DeleteFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting line by swipe.
        /// </summary>
        internal static string DeletingLine {
            get {
                return ResourceManager.GetString("DeletingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edit box is empty.
        /// </summary>
        internal static string EmptyCell {
            get {
                return ResourceManager.GetString("EmptyCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list is empty.
        /// </summary>
        internal static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish moving line.
        /// </summary>
        internal static string FinishMovingLine {
            get {
                return ResourceManager.GetString("FinishMovingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get list from gmail.
        /// </summary>
        internal static string GetListFromGmail {
            get {
                return ResourceManager.GetString("GetListFromGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail.
        /// </summary>
        internal static string Gmail {
            get {
                return ResourceManager.GetString("Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmail client id.
        /// </summary>
        internal static string GmailClientId {
            get {
                return ResourceManager.GetString("GmailClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string GmailFrom {
            get {
                return ResourceManager.GetString("GmailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string GmailSubject {
            get {
                return ResourceManager.GetString("GmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input list.
        /// </summary>
        internal static string InputList {
            get {
                return ResourceManager.GetString("InputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to input.
        /// </summary>
        internal static string MoveToInput {
            get {
                return ResourceManager.GetString("MoveToInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New store.
        /// </summary>
        internal static string NewStore {
            get {
                return ResourceManager.GetString("NewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No error.
        /// </summary>
        internal static string NoError {
            get {
                return ResourceManager.GetString("NoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output list.
        /// </summary>
        internal static string OutputList {
            get {
                return ResourceManager.GetString("OutputList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value.
        /// </summary>
        internal static string PleaseSelectValue {
            get {
                return ResourceManager.GetString("PleaseSelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Duplicities.
        /// </summary>
        internal static string RemoveDuplicities {
            get {
                return ResourceManager.GetString("RemoveDuplicities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running....
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        internal static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected store.
        /// </summary>
        internal static string SelectedStore {
            get {
                return ResourceManager.GetString("SelectedStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select store:.
        /// </summary>
        internal static string SelectStore {
            get {
                return ResourceManager.GetString("SelectStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show finished.
        /// </summary>
        internal static string ShowFinished {
            get {
                return ResourceManager.GetString("ShowFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter word/expression.
        /// </summary>
        internal static string SpeechDelimiter {
            get {
                return ResourceManager.GetString("SpeechDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start listening.
        /// </summary>
        internal static string StartListening {
            get {
                return ResourceManager.GetString("StartListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start moving line.
        /// </summary>
        internal static string StartMovingLine {
            get {
                return ResourceManager.GetString("StartMovingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop listening.
        /// </summary>
        internal static string StopListening {
            get {
                return ResourceManager.GetString("StopListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a wide swipe if you want to delete the line.
        /// </summary>
        internal static string SwipeDelete {
            get {
                return ResourceManager.GetString("SwipeDelete", resourceCulture);
            }
        }
    }
}
